
project: RLxxxx

env:
    # assign global environment variables, which will apply to all jobs
    # and even the user script is about to be exectued
    phone: 09123

debug:
    True

jobs:
    monitor_svn:
        # name:
        #     monitor a svn repo
        job_config:
            continue_on_error: false
            cwd: 
                # specified a wokring directory to run commands when a event occurs
                null
            env:
                # local environment variables, which will also inherit from the global environment variables
                null
        monitor:
            # schedule: "*/5 * * * * * *"
            schedule: every 5 seconds
            type: svn
            targets: 
                - ./unittest/svn_local2
                - ./notgannamatch
                # - ./unittest/two/trunk/test1/
                # - ./unittest/two/trunk/test2/add.ext
        on_events:
            # events will be trigered if monitor detects any changes on targets
            # event type: added, modified, removed or any
            any: 
                - name: search time
                  cmd: ls -al .
                - name: print somthing
                  cmd: echo "somthing"
                # - name: search 123 with error
                #   cmd: grep 123  __main__.py
        on_error:
            name: do somthing if exectued cmd returns a error
            cmd: echo "error"
            # cmd: ./expensive.sh
              # cmd: send -phone ${phone} -msg "error when ..."
        on_success:
            name: do somthing if all of cmds are success
            cmd: echo "YES"


            

          



