
project: RLxxxx

env:
    # assign global environment variables, which will apply to all jobs
    # and even the user script is about to be exectued
    phone: 0988639378

jobs:
    monitor_svn:
        name: #
            monitor a svn repo
        config:
            working_directory: 
                # specified a wokring directory to run commands when a event occurs
                null
            continue_on_error: false
            env:
                # local environment variables, which will also inherit from the global environment variables
                null
        monitor:
            schedule: "*/2 * * * * * *"
            type: svn
            targets: 
                - ./unittest/svn_local2
                # - ./unittest/two/trunk/test1/
                # - ./unittest/two/trunk/test2/add.ext
        on_event:
            # events will be trigered if monitor detects any changes on targets
            # event type: added, modified, removed or any
            any: 
                - name: search time
                  cmd: ./test.sh
                # - name: print somthing
                #   cmd: ./print.sh
                # - name: search 123 with error
                #   cmd: grep 123  __main__.py
        on_error:
            name: do somthing if exectued cmd returns a error
            cmd: ./print_error.sh
            # cmd: ./expensive.sh
              # cmd: send -phone ${phone} -msg "error when ..."
        on_success:
            name: do somthing if all of cmds are success
            cmd: echo "YES"


            

          



